### ISSUE TITLE
finalize support for Esri REST

### ISSUE THREAD

**Issue by capooti** [cga-harvard/Hypermap-Registry#8]
Both service and folder of services.

@bglewis : Esri REST includes much more information than WMS/WMTS... services, for example Geometry Type (Points, Lines, Polygons).
Should we track this additional information?

**Comment by blewis** [comment]
Perhaps some.  Let’s talk.

Ben Lewis
Center for Geographic Analysis, Harvard University
1737 Cambridge St, K016
617.496.3089
blewis@cga.harvard.edu<mailto:blewis@cga.harvard.edu>
http://gis.harvard.edu<http://gis.harvard.edu/>
http://worldmap.harvard.edu<http://worldmap.harvard.edu/>
